"""add debt_groups and debt_group_members tables

Revision ID: 9458ccd9337c
Revises: b2c3d4e5f6a7
Create Date: 2026-03-24 21:21:00.234587
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9458ccd9337c'
down_revision: Union[str, None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debt_groups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debt_groups_user_id'), 'debt_groups', ['user_id'], unique=False)
    op.create_table('debt_group_members',
    sa.Column('debt_group_id', sa.Uuid(), nullable=False),
    sa.Column('debt_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['debt_group_id'], ['debt_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['debt_id'], ['debts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('debt_group_id', 'debt_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('debt_group_members')
    op.drop_index(op.f('ix_debt_groups_user_id'), table_name='debt_groups')
    op.drop_table('debt_groups')
    # ### end Alembic commands ###
