"""add category_mapping and is_default to csv_mappings

Revision ID: f68c31568ad7
Revises: 9458ccd9337c
Create Date: 2026-03-26 00:44:04.965366
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

revision: str = "f68c31568ad7"
down_revision: Union[str, None] = "9458ccd9337c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("csv_mappings", sa.Column("category_mapping", sa.JSON(), nullable=True))
    op.add_column(
        "csv_mappings", sa.Column("is_default", sa.Boolean(), server_default=sa.text("false"), nullable=False)
    )
    op.alter_column("csv_mappings", "user_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("csv_mappings", "user_id", existing_type=sa.UUID(), nullable=False)
    op.drop_column("csv_mappings", "is_default")
    op.drop_column("csv_mappings", "category_mapping")
    # ### end Alembic commands ###
